version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.14 #
    environment:
      TEST_RESULTS: /tmp/test-results
      LOGLEVEL: TRACE
    steps:
      - checkout # check out source code to working directory
      - run: go build github.com/simonmittag/jabba
      - run: go install github.com/simonmittag/jabba/cmd/jabba
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: "Run tests with coverage report"
          command: |
            go test -cover -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts